---
- name: Install Unzip
  apt: 
    name: unzip
    state: latest
 
- name: Terraform Binary Install
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
    dest: /usr/bin
    remote_src: True