#!/usr/bin/env python3 
import os
import subprocess
import time

# Imported from Engima's Launch Function
print("What would like to name this MP Instance?")
mpname = input("Name: ")
print("How many CPUs would you like to allocate?")
print("The minimum CPUs is 1 and the default CPU allocation is 1 if left blank")
mpcpu = input("CPUs: ")
print("How much Memory would you like to allocate?")
print("Please use the suffixes of K,M or G in declaring memory.") 
print("The minimum Memory is 128M and the default is 1G if left blank")
mpmem = input("Memory: ")
print("How much disk space would you like to allocate?")
print("Please use the suffixes of K,M or G in declaring disk space.")
print("The minimum storage is 512M and the default is 5G")
mpdisk = input("Space: ")
if mpcpu == '':
    mpcpu = 1  
if mpmem == '': 
    mpmem = '128M'
if mpdisk == '':
    mpdisk = '5G'
print(f"To finalize the creation of this MP Instance,please verify the following settings:")
print(f"Name: {mpname}")
print(f"CPUs: {mpcpu}")
print(f"Memory: {mpmem}")
print(f"Disk Space: {mpdisk}") 
mpfinal = input("Is this correct? y/n?: ")
if mpfinal == "y":
    print("Creating MP Instance with the following settings")
    os.system(f"multipass launch -n {mpname} -c {mpcpu} -m {mpmem} -d {mpdisk} --cloud-init /home/warpwing/YMLs/CloudInit/base.yml")
    print(f"Instance {mpname} created!")
    time.sleep(2)
else: 
    print("Going back to the main menu!") # I'll work on a fix later that allows you to either resubmit settings or go back to the main menu.
    time.sleep(2)

os.system("clear")
print("---------------------------------------------------------------------------")
x = subprocess.Popen("multipass list", shell=True, stdout=subprocess.PIPE)
subprocess_return = x.stdout.read()
print(subprocess_return.decode("ascii"))
print("---------------------------------------------------------------------------")
subprocess.call("ansireg")
