#cloud-config
# This is the base cloudinstance for my MP VMs

# Add default user
users: 
  - name: ubuntu
    ssh_import_id: warpwing 
    ssh_authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvc+IKkZaXtM86NCafo8tJ9hApKnBplgj1wbdxPPXm2T5W1O00ompsVS88a5mOrDnleCo0+WbYeYM8OPL1tPZEXgGmX5tDq3p5xkil45GmmclqVvQaF+mw97ZE1G1x+N6hQZJv3H+LFgYu4A5iMhZs1p9E+7uR0yHrC5Zw7q1ON1ITxG+XMF3APeKCTptTCAMPMQ2621tCXaB92361Gbe/J8wvqmnYhIlI8hn1/i5stxReQWpe+NElU3wO6WGanEw34S/rdE7EgezXmhwiZ4IysC05OQOcMzwm+EEn0Z+vc6MnpnempZg6fHxgI2mnIYFetJR9uy3uMC3ejZ06W9dhljwkcHsMgm5ego9GfU8huU3bpTKfr9voGsxC4kKgKtRvaiUDtbBvW+78mTHU+90GHYoo5Wr1EWYnWphJhLtLHJjUV6aZXX94QNUG31kSOh1ufL9R6jP5M6PSDNoTB6ZMhjWeQ2o7BM2k1dV59kghmIr6j4+kHdNsdysZBzMiWm0= warpwing@sentinel
