apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn
  name: longhorn
spec:
  type: LoadBalancer
  selector:
    app: longhorn
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
