apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: trident
  template:
    metadata:
      labels:
        app: trident
    spec:
      containers:
      - image: nginx:latest
        name: trident
        ports:
        - containerPort: 80