apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident
spec:
  replicas: 0
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: trident
  template:
    metadata:
      labels:
        app: trident
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: warpwing/longhornprod
        imagePullPolicy: "Always"
        name: trident
        ports:
        - containerPort: 5000