apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: trident
  template:
    metadata:
      labels:
        app: trident
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: warpwing/longhornprod
        imagePullPolicy: "Always"
        name: trident
        ports:
        - containerPort: 5000