
- name: Updating Packages 
  apt:  
    upgrade: dist
    force_apt_get: yes 
- name: Update apt-cache 
  apt: 
    update_cache: yes
- name: Downloading and Deploying Docker Helper Script
  shell: curl https://get.docker.com -o get-docker.sh && sh get-docker.sh
  args:
    warn: no
- name: Add User to Docker Group 
  shell: sudo usermod -aG docker $USER
    