---
- hosts: all
  become: true
  tasks:
  - name: Install basic packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  - name: Add an apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add apt repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: Install docker and dependencies
    apt:
      name: 
        - docker-ce
      state: present
      update_cache: yes
