---
- name: k3s Deployment
  hosts: kubernetes
  remote_user: warpwing

  tasks: 
  - name: Deploy k3s over curl
    shell: curl -sfL https://get.k3s.io | sh -
  - name: Deploy k3s server
    shell: sudo k3s server --write-config 
